/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ExperienceEntry {
  company?: string;
  position?: string;
  startDate?: string;
  endDate?: string;
  description?: string;
}
