/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type Search1Params = {
text: string;
area: string;
page: number;
perPage: number;
providers?: string[];
};
