/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SearchExperience =
  (typeof SearchExperience)[keyof typeof SearchExperience];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchExperience = {
  NO_EXPERIENCE: "NO_EXPERIENCE",
  BETWEEN_1_AND_3: "BETWEEN_1_AND_3",
  BETWEEN_3_AND_6: "BETWEEN_3_AND_6",
  MORE_THAN_6: "MORE_THAN_6",
} as const;
