/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Search1Experience } from "./search1Experience";
import type { Search1Schedule } from "./search1Schedule";
import type { Search1Education } from "./search1Education";

export type Search1Params = {
  text: string;
  area: string;
  page: number;
  perPage: number;
  providers?: string[];
  salaryFrom?: number;
  salaryTo?: number;
  ageFrom?: number;
  ageTo?: number;
  experience?: Search1Experience;
  schedule?: Search1Schedule;
  education?: Search1Education;
};
