// This file is auto-generated by @hey-api/openapi-ts

export const $ExperienceEntry = {
    type: 'object',
    properties: {
        company: {
            type: 'string'
        },
        position: {
            type: 'string'
        },
        startDate: {
            type: 'string',
            format: 'date-time'
        },
        endDate: {
            type: 'string',
            format: 'date-time'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const $Resume = {
    type: 'object',
    properties: {
        source: {
            type: 'string'
        },
        externalId: {
            type: 'string'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        position: {
            type: 'string'
        },
        salary: {
            type: 'integer',
            format: 'int32'
        },
        currency: {
            type: 'string'
        },
        city: {
            type: 'string'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        url: {
            type: 'string'
        },
        age: {
            type: 'integer',
            format: 'int32'
        },
        experienceMonths: {
            type: 'integer',
            format: 'int32'
        },
        gender: {
            type: 'string'
        },
        educationLevel: {
            type: 'string'
        },
        experience: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ExperienceEntry'
            }
        }
    }
} as const;

export const $Vacancy = {
    type: 'object',
    properties: {
        source: {
            type: 'string'
        },
        externalId: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        company: {
            type: 'string'
        },
        companyUrl: {
            type: 'string'
        },
        city: {
            type: 'string'
        },
        salaryFrom: {
            type: 'integer',
            format: 'int32'
        },
        salaryTo: {
            type: 'integer',
            format: 'int32'
        },
        currency: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        experienceReq: {
            type: 'string'
        },
        employmentType: {
            type: 'string'
        },
        schedule: {
            type: 'string'
        },
        publishedAt: {
            type: 'string',
            format: 'date-time'
        },
        url: {
            type: 'string'
        }
    }
} as const;