// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { PostYookassaWebhookData, PostYookassaWebhookResponse, GetResumeFavoritesResponse, PostResumeFavoritesData, PostResumeFavoritesResponse, DeleteResumeFavoritesBySourceByExternalIdData, DeleteResumeFavoritesBySourceByExternalIdResponse, PostPaymentsProResponse, GetFavoritesResponse, PostFavoritesData, PostFavoritesResponse, DeleteFavoritesBySourceByExternalIdData, DeleteFavoritesBySourceByExternalIdResponse, PostAuthRegisterData, PostAuthRegisterResponse, PostAuthLoginData, PostAuthLoginResponse, GetVacanciesData, GetVacanciesResponse, GetResumesData, GetResumesResponse } from './types.gen';

export class YooKassaWebhookService {
    /**
     * @param data The data for the request.
     * @param data.contentHmacSha256
     * @param data.requestBody
     * @returns string OK
     * @throws ApiError
     */
    public static postYookassaWebhook(data: PostYookassaWebhookData): CancelablePromise<PostYookassaWebhookResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/yookassa/webhook',
            headers: {
                'Content-Hmac-Sha256': data.contentHmacSha256
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}

export class ResumeFavoriteControllerService {
    /**
     * @returns Resume OK
     * @throws ApiError
     */
    public static getResumeFavorites(): CancelablePromise<GetResumeFavoritesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/resume-favorites'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static postResumeFavorites(data: PostResumeFavoritesData): CancelablePromise<PostResumeFavoritesResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/resume-favorites',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.source
     * @param data.externalId
     * @returns unknown OK
     * @throws ApiError
     */
    public static deleteResumeFavoritesBySourceByExternalId(data: DeleteResumeFavoritesBySourceByExternalIdData): CancelablePromise<DeleteResumeFavoritesBySourceByExternalIdResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/resume-favorites/{source}/{externalId}',
            path: {
                source: data.source,
                externalId: data.externalId
            }
        });
    }
    
}

export class PaymentControllerService {
    /**
     * @returns string OK
     * @throws ApiError
     */
    public static postPaymentsPro(): CancelablePromise<PostPaymentsProResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/payments/pro'
        });
    }
    
}

export class FavoriteControllerService {
    /**
     * @returns Vacancy OK
     * @throws ApiError
     */
    public static getFavorites(): CancelablePromise<GetFavoritesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/favorites'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static postFavorites(data: PostFavoritesData): CancelablePromise<PostFavoritesResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/favorites',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.source
     * @param data.externalId
     * @returns unknown OK
     * @throws ApiError
     */
    public static deleteFavoritesBySourceByExternalId(data: DeleteFavoritesBySourceByExternalIdData): CancelablePromise<DeleteFavoritesBySourceByExternalIdResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/favorites/{source}/{externalId}',
            path: {
                source: data.source,
                externalId: data.externalId
            }
        });
    }
    
}

export class AuthControllerService {
    /**
     * @param data The data for the request.
     * @param data.email
     * @param data.pwd
     * @returns unknown OK
     * @throws ApiError
     */
    public static postAuthRegister(data: PostAuthRegisterData): CancelablePromise<PostAuthRegisterResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/auth/register',
            query: {
                email: data.email,
                pwd: data.pwd
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.email
     * @param data.pwd
     * @returns unknown OK
     * @throws ApiError
     */
    public static postAuthLogin(data: PostAuthLoginData): CancelablePromise<PostAuthLoginResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/auth/login',
            query: {
                email: data.email,
                pwd: data.pwd
            }
        });
    }
    
}

export class VacancyControllerService {
    /**
     * @param data The data for the request.
     * @param data.text
     * @param data.area
     * @param data.page
     * @param data.perPage
     * @param data.providers
     * @returns Vacancy OK
     * @throws ApiError
     */
    public static getVacancies(data: GetVacanciesData): CancelablePromise<GetVacanciesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/vacancies',
            query: {
                text: data.text,
                area: data.area,
                page: data.page,
                perPage: data.perPage,
                providers: data.providers
            }
        });
    }
    
}

export class ResumeControllerService {
    /**
     * @param data The data for the request.
     * @param data.text
     * @param data.area
     * @param data.page
     * @param data.perPage
     * @param data.providers
     * @returns Resume OK
     * @throws ApiError
     */
    public static getResumes(data: GetResumesData): CancelablePromise<GetResumesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/resumes',
            query: {
                text: data.text,
                area: data.area,
                page: data.page,
                perPage: data.perPage,
                providers: data.providers
            }
        });
    }
    
}