// This file is auto-generated by @hey-api/openapi-ts

export type ExperienceEntry = {
    company?: string;
    position?: string;
    startDate?: string;
    endDate?: string;
    description?: string;
};

export type Resume = {
    source?: string;
    externalId?: string;
    firstName?: string;
    lastName?: string;
    position?: string;
    salary?: number;
    currency?: string;
    city?: string;
    updatedAt?: string;
    url?: string;
    age?: number;
    experienceMonths?: number;
    gender?: string;
    educationLevel?: string;
    experience?: Array<ExperienceEntry>;
};

export type Vacancy = {
    source?: string;
    externalId?: string;
    title?: string;
    company?: string;
    companyUrl?: string;
    city?: string;
    salaryFrom?: number;
    salaryTo?: number;
    currency?: string;
    description?: string;
    experienceReq?: string;
    employmentType?: string;
    schedule?: string;
    publishedAt?: string;
    url?: string;
};

export type PostYookassaWebhookData = {
    contentHmacSha256: string;
    requestBody: string;
};

export type PostYookassaWebhookResponse = string;

export type GetResumeFavoritesResponse = Array<Resume>;

export type PostResumeFavoritesData = {
    requestBody: Resume;
};

export type PostResumeFavoritesResponse = unknown;

export type DeleteResumeFavoritesBySourceByExternalIdData = {
    externalId: string;
    source: string;
};

export type DeleteResumeFavoritesBySourceByExternalIdResponse = unknown;

export type PostPaymentsProResponse = string;

export type GetFavoritesResponse = Array<Vacancy>;

export type PostFavoritesData = {
    requestBody: Vacancy;
};

export type PostFavoritesResponse = unknown;

export type DeleteFavoritesBySourceByExternalIdData = {
    externalId: string;
    source: string;
};

export type DeleteFavoritesBySourceByExternalIdResponse = unknown;

export type PostAuthRegisterData = {
    email: string;
    pwd: string;
};

export type PostAuthRegisterResponse = {
    [key: string]: unknown;
};

export type PostAuthLoginData = {
    email: string;
    pwd: string;
};

export type PostAuthLoginResponse = {
    [key: string]: unknown;
};

export type GetVacanciesData = {
    area: string;
    page: number;
    perPage: number;
    providers?: Array<(string)>;
    text: string;
};

export type GetVacanciesResponse = Array<Vacancy>;

export type GetResumesData = {
    area: string;
    page: number;
    perPage: number;
    providers?: Array<(string)>;
    text: string;
};

export type GetResumesResponse = Array<Resume>;

export type $OpenApiTs = {
    '/yookassa/webhook': {
        post: {
            req: PostYookassaWebhookData;
            res: {
                /**
                 * OK
                 */
                200: string;
            };
        };
    };
    '/resume-favorites': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<Resume>;
            };
        };
        post: {
            req: PostResumeFavoritesData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/resume-favorites/{source}/{externalId}': {
        delete: {
            req: DeleteResumeFavoritesBySourceByExternalIdData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/payments/pro': {
        post: {
            res: {
                /**
                 * OK
                 */
                200: string;
            };
        };
    };
    '/favorites': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<Vacancy>;
            };
        };
        post: {
            req: PostFavoritesData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/favorites/{source}/{externalId}': {
        delete: {
            req: DeleteFavoritesBySourceByExternalIdData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/auth/register': {
        post: {
            req: PostAuthRegisterData;
            res: {
                /**
                 * OK
                 */
                200: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/auth/login': {
        post: {
            req: PostAuthLoginData;
            res: {
                /**
                 * OK
                 */
                200: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/vacancies': {
        get: {
            req: GetVacanciesData;
            res: {
                /**
                 * OK
                 */
                200: Array<Vacancy>;
            };
        };
    };
    '/resumes': {
        get: {
            req: GetResumesData;
            res: {
                /**
                 * OK
                 */
                200: Array<Resume>;
            };
        };
    };
};